### ISSUE TITLE
Fix screens.rpy

### ISSUE THREAD

**Issue by Crackwhacker** [kfcpaladin/sze-the-game#6]
Currently not a primary issue, but would be great if we could figure out how to fix the grid over full or not full enough issue. Use the comments for suggestions.

**Comment by kfcpaladin** [comment]
Please fix stats, they are core to the enjoyment of the game

**Comment by Crackwhacker** [comment]
Just out of curiosity, how did you fix stats?

**Comment by kfcpaladin** [comment]
I kinda just deleted the whole nodule and reweote it again

_Sent from my Samsung SM-N920G using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
